# nginx del frontend, escuchando en 8080 (igual que el containerPort de ECS).
server {
    listen 8080;
    server_name _;

    location / {
        root  /usr/share/nginx/html;
        index index.html;
    }
}
